// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://glcbjimltumejbmlxstx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdsY2JqaW1sdHVtZWpibWx4c3R4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc3MzM2NzYsImV4cCI6MjA1MzMwOTY3Nn0.ZKnGEczczpCt-VLXzfFlNfX6K9w934y1asuE2YG7Ze8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);